### ISSUE TITLE
Too many errors: Correct version of libraries : ceres solver etc

### ISSUE THREAD

**Issue by ChidanandKumarKS** [Li-Jesse-Jiaze/ov_hloc#1]
Hi,

Got too many errors. Woud like to know
a) version of gcc
b) ceres-solver version
c) torch version etc

Kindkly do the nbeedful

**Comment by Li-Jesse-Jiaze** [comment]
My bad. I'll update the detailed environment configuration steps in the Dependencies section of the readme later.

I'm actually planning to replace torchscript with onnx, which will make the steps to configure the environment a bit easier and facilitate acceleration through other hardware.

**Comment by Li-Jesse-Jiaze** [comment]
Hi, I have updated the readme. Due to the use of libtorch, the dependency installation is a bit complicated, so I recommend restarting with a clean ubuntu system.

If you encounter any other problems during the installation steps, please put the error message along with the issue.

btw my dependency version are like 
- gcc version 7.5.0
- ceres-solver version 2.1.0
- pytorch version 1.12.1

**Comment by ChidanandKumarKS** [comment]
Thanks will try out the versions
